language: node_js
node_js:
- '10'
- node
before_install:
- npm i -g npm@latest
install:
- npm install
script:
- npm run build
deploy:
  provider: heroku
  api_key:
    secure: DkmPacoj0Q3aBwUjMmNB8SbeWrv92qQGipKrIww0xgSvNeawfNdOm46e1t/bJ0mRpxSMyNxMItkmBfxGa0UBb15bydn5dfMMWdwWanC04KkAzSqJJYGVxNy9q/lDCCxDWyEKaig9CDTP2xVtMfZ8jTq3kNEruLmLp9720JVm0pm//RFqJwypNF+3a6PXkkajgXYYy2/Cw/XC13TMDynuNhzChwz549d/NFpgXCp1st0vXf6m0SF3VwYFyqFxhu0RdNyWS5977gpr4T77GmvaVg8hsTx+iz0hcwG1Th1PZvTjy4JjXVjKz5Zh5ziz7wMyUmKTbEUWFGeoQUofuvnrREIllPhcwOY5Q6/CUxUfjZvuCHQU4UviAdRKm8cByFcijF3gaTUIPPJIZVcXbfOeIGECFoo6s/RZevPNDhjbUXc5aSGDqYGLo1D8adc3QMrQ3YliOM7KL+vIm5eV+aNHuIg3WXIt0GyFiD/4CopWRnnfSDMr73BXcJGoZCbmuyos8u8fBxhp1DFhZQ4su1zvbBgeBMx4B+bcG3yeDIUfXSwUf7QovEG7CFMqc+p8riCkmCh1uTM5xlke1hvwOSJzf90qqciqMAu3+FllInM10bDqXzyf7J6AcabfD1Se3BxqHsJxJKaAQV+W8FZYgyMLy7/xu3bTPzrukgBQEy5d7qw=
  app: task-board-backend
  on:
    branch: master
